preferred_syntax = :sass
http_path = '/'
css_dir = 'dist/css'
sass_dir = 'assets/sass'
images_dir = 'assets/images'
javascripts_dir = 'assets/js'
relative_assets = false
line_comments = true
# output_style = :compressed